# Change these first
owner: jheeree
repo: uptime

sites:
  - name: Blog
    url: https://jhere.io
    expectedStatusCodes:
      - 403
  - name: OpenCTI
    url: https://opencti.jhere.tech
    expectedStatusCodes:
      - 403

status-website:
  theme: night
  cname: status.jhere.io
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: Uptime
  navbar:
    - title: Status
      href: /

i18n:
  activeIncidents: Incidentes activos
  allSystemsOperational: Todos los sistemas están operativos
  loading: Cargando
  overallUptimeTitle: Actividad general
  averageResponseTime: "Tiempo promedio de respuesta: $TIMEms"
  liveStatus: Estado
  duration24H: 24h
  duration7D: 7d
  duration30D: 30d
  duration1Y: 1y
  durationAll: todo
  duration: Duracion
  durationMin: $DURATION minutos
  incidentCompleted: Completado
  incidentScheduled: Programado
  footer: Este sitio es open source, gracias a [Upptime](https://upptime.js.org)
